<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statement &mdash; {{ $client->name }}</title>
    @include('pdf._styles')
</head>
<body>

@include('pdf._header', [
    'docTitle' => 'Statement',
    'metaRows' => [
        'Customer'  => $client->company_name ?? $client->name,
        'Period'    => $startDate . ' – ' . $endDate,
        'Generated' => $generatedAt->format('d M Y'),
    ],
])

{{-- BILL TO --}}
<div class="pdf-section-label">Bill To</div>
<div class="pdf-gap-6">&nbsp;</div>
<div class="pdf-name">{{ $client->company_name ?? $client->name }}</div>
<div class="pdf-body">{{ $client->address ?? 'Malaysia' }}</div>
@if($client->phone)
    <div class="pdf-body">{{ $client->phone }}</div>
@endif

<div class="pdf-gap-24">&nbsp;</div>

{{-- TRANSACTIONS --}}
<table class="pdf-table">
    <thead>
        <tr>
            <th style="width:19%;">Invoice No.</th>
            <th style="width:12%;">Issue Date</th>
            <th style="width:12%;">Due Date</th>
            <th class="num" style="width:15%;">Amount</th>
            <th class="num" style="width:14%;">Paid</th>
            <th class="num" style="width:15%;">Balance</th>
            <th style="width:13%;">Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($invoices as $invoice)
            @php($balance = (float) $invoice->total_amount - (float) $invoice->paid_amount)
            <tr>
                <td>{{ $invoice->invoice_number }}</td>
                <td>{{ $invoice->issue_date->format('d M Y') }}</td>
                <td>{{ $invoice->due_date->format('d M Y') }}</td>
                <td class="num">{{ number_format((float) $invoice->total_amount, 2) }}</td>
                <td class="num">{{ number_format((float) $invoice->paid_amount, 2) }}</td>
                <td class="num {{ $balance > 0 ? 'pdf-due' : '' }}">{{ number_format($balance, 2) }}</td>
                <td>{{ ucfirst(str_replace('_', ' ', $invoice->status)) }}</td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Totals</td>
            <td class="num">{{ number_format($summary['total_invoiced'], 2) }}</td>
            <td class="num">{{ number_format($summary['total_paid'], 2) }}</td>
            <td class="num">{{ number_format($summary['total_outstanding'], 2) }}</td>
            <td></td>
        </tr>
    </tfoot>
</table>

<div class="pdf-gap-24">&nbsp;</div>

{{-- OUTSTANDING SUMMARY --}}
<table class="pdf-totals">
    <tr class="subtotal">
        <td class="label">Total Outstanding</td>
        <td class="value">{{ number_format($summary['total_outstanding'], 2) }}</td>
    </tr>
    <tr class="grand">
        <td class="label">Total Overdue</td>
        <td class="value {{ $summary['total_overdue'] > 0 ? 'pdf-due' : '' }}">RM {{ number_format($summary['total_overdue'], 2) }}</td>
    </tr>
</table>

@include('pdf._footer', [
    'footerNote' => 'Generated by ' . $generatedBy . ' on ' . $generatedAt->format('d M Y, H:i') . ' · Rotikaya Sales Tracking & Management System',
])

</body>
</html>
