<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title ?? 'Report' }}</title>
    @include('pdf._styles')
</head>
<body>

@php
    $generatedBy = $generatedBy ?? (request()->user()?->name ?? 'System');
    $metaRows = [
        'Period'       => $period ?? 'All Time',
        'Generated'    => $date ?? now()->format('d M Y'),
        'Generated By' => $generatedBy,
    ];
@endphp

@include('pdf._header', [
    'docTitle' => $title ?? 'Report',
    'metaRows' => $metaRows,
])

@yield('content')

@include('pdf._footer', [
    'footerNote' => 'Generated by Rotikaya Sales Tracking & Management System on ' . now()->format('d M Y, H:i'),
])

</body>
</html>
